---
title: Soffers' research
format:
    html:
        format-links: false
---

Welcome to the **Soffers Lab**. We study the gene-regulatory mechanisms that govern the development of neuronal circuits in *Drosophila*, combining genetic experimetnal approaches with electron microscopy connectomics and computation.

## Research interests

- The role of transcription and epigenetic factors during wiring of sensorimotor circuits
- Activity-dependent synaptogenesis and circuit refinement
- Electron microscopy connectomics at synaptic resolution
- Computational models of circuit assembly rules

## Recent news

| Date | Event |
|------|-------|
|2026-04-15| Dr Soffers joins the STEM outreach event for an extended weekend: Pueblo Brain Science- New Mexico|
| 2026-03-09 | NINDS K99/R00 awarded to Jelly Soffers|
| 2026-03-18 | "A Developmental Atlas of the Drosophila Nerve Cord Uncovers a Global Temporal Code for Neuronal Identity" preprint posted on bioRxiv|
| 2025-03-08 | "A Ubiquitin network safeguards cell identity by continuously degrading a stem-cell related translational machinery" preprint posted on bioRxiv



## Contact

- **Email:** [j.soffers@umkc.edu](mailto:j.soffers@umkc.edu)
- **Office:** University of Missouri  Kansas- CityCorane Farm Research, Spencer Chemistry Building, Room 509
- **Address:** 5009 Rockhill Rd, Kanas City, MO 64111